config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_omniauth_user_session
  end  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'  

  root to: "books#index"

  resources :users do
    post 'change_billing_address', :to => 'users#change_billing_address', :as => :change_billing_address, on: :collection    
    post 'change_shipping_address', :to => 'users#change_shipping_address', :as => :change_shipping_address, on: :collection 
    post 'change_email', :to => 'users#change_email', :as => :change_email, on: :collection 
    post 'change_password', :to => 'users#change_password', :as => :change_password, on: :collection    
  end
  resources :books do
    get 'index_shop', on: :collection
  end

  resources :orders do
    get 'cart', on: :collection
    get 'checkout', on: :collection
  end
  
  post "ratings" => 'ratings#create', as: :create_rating

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :credit_card
  belongs_to :billing_address, class: Address
  belongs_to :shipping_address, class: Address 
  has_many :order_items
  has_many :books, through: :order_items


  validates :total_price, presence: true
  validates :shipping_type, presence: true
  validates :number, presence: true
  validates :completed_at, presence: true

  after_initialize :set_defaults

  def set_defaults
    self.number ||= Random::rand().to_s[2..11]
    self.completed_at ||= Date.today
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def show
    @order = Order.find(params[:id])
    authorize! :read, @order
    @ordered_items = @order.order_items
    @items = Array.new
    @qty = Array.new
    case @order.shipping_type
      when 'UPS Ground'
        @shipping_price = 5
      when 'UPS Two Days'
        @shipping_price = 10
      when 'UPS One Day'
        @shipping_price = 15
      else
        @shipping_price = 0
      end
    @ordered_items.each do |i|
      @items.push(Book.find(i.book_id))
      @qty.push(i.quantity)
    end
  end

  def index
    @total = 0
    @items = Array.new
    @qty = Array.new    
    if cookies['ordered_items']
      cookies['ordered_items'].split(',').each do |item|
        order_item = item.split('|')
        book = Book.find(order_item[0])
        @items.push(book)
        @qty.push(order_item[1])
        @total += book.price * order_item[1].to_i
      end      
    end
    @orders_in_progress = Order.where(user_id: current_user.id, state: 'in progress')
    @has_no_orders = Order.where(user_id: current_user.id, state: ['in progress', 'in delivery', 'delivered']).empty?
    @orders_in_delivery = Order.where(user_id: current_user.id, state: 'in delivery')
    @orders_delivered = Order.where(user_id: current_user.id, state: 'delivered')
  end

  def create
    bil_address = Address.new({ address1: order_params[:bil_street], city: order_params[:bil_city], 
      country: order_params[:bil_country], zip_code: order_params[:bil_zip],
      mobile_number: order_params[:bil_mobile] })
    unless bil_address.save
      render "shared/shared/something_went_wrong"
    end
    ship_address = Address.new({  address1: order_params[:ship_street],
     city: order_params[:ship_city], country: order_params[:ship_country],
     zip_code: order_params[:ship_zip] })
    unless ship_address.save
      render "shared/shared/something_went_wrong"
    end    
    credit_card = CreditCard.new({ number: order_params[:card_number],
     expiration_date: Date.new(order_params[:card_exp_year].to_i, order_params[:card_exp_month].to_i, 1),
     user_id: current_user.id })
    unless credit_card.save!
      render "shared/shared/something_went_wrong"
    end    
    order = Order.new({ total_price: order_params[:total_price].to_d,
      billing_address_id: bil_address.id, shipping_address_id: ship_address.id,
        user_id: current_user.id, credit_card_id: credit_card,
        shipping_type: order_params[:shipping_type] })
    unless order.save!
      render "shared/shared/something_went_wrong"
    end
    cookies[:ordered_items].split(',').each do |item|
      book_id = item.split('|')[0].to_i
      qty = item.split('|')[1].to_i
      order_item = OrderItem.new({ order_id: order.id, book_id: book_id,
      quantity: qty, price: Book.find(book_id).price })
      order_item.save!
    end
    cookies.delete :ordered_items, path: '/'
    render :js => "window.location = '#{index_shop_books_path}'"
  end

  def checkout
    if !cookies['ordered_items']
      redirect_to index_shop_books_path 
    end 
    user = current_user
    address = current_user.billing_address
    @first_name = user.firstname
    @last_name = user.lastname
    unless address.nil?
      @street = address.address1
      @city = address.city
      @zip = address.zip_code
      @phone_number = address.mobile_number
      @country = address.country
    end
    @total = 0
    @items = Array.new
    @qty = Array.new
    if cookies['ordered_items']
      cookies['ordered_items'].split(',').each do |item|
        order_item = item.split('|')
        book = Book.find(order_item[0])
        @items.push(book)
        @qty.push(order_item[1])
        @total += book.price * order_item[1].to_i
      end      
    end
  end

  def cart 
    @total = 0
    @items = Array.new
    @qty = Array.new
    if cookies['ordered_items']
      cookies['ordered_items'].split(',').each do |item|
        order_item = item.split('|')
        book = Book.find(order_item[0])
        @items.push(book)
        @qty.push(order_item[1])
        @total += book.price * order_item[1].to_i
      end
    end
  end

private

  def order_params
    params.require(:order).permit(:card_exp_year, :card_exp_month, :card_number,
      :ship_country, :ship_zip, :ship_city, :ship_street, :bil_mobile, :bil_country, :bil_zip,
      :bil_city, :bil_street, :total_price, :shipping_type)
  end  
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_orders_status.html.erb
<div class="text-align-center width100 display-inline-block">
  <div class="float-left width20">
    <h5>NUMBER</h5>    
  </div>
  <div class="float-left width20">
    <h5>COMPLETED AT</h5>
  </div>
  <div class="float-left width20">
    <h5>TOTAL</h5>
  </div>

  <% orders.each do |order| %>
    <div class="clear-both"></div>
    <div class="float-left width20">
      <a><%=order.number%></a>
    </div>
    <div class="float-left width20">
      <p><%=order.completed_at%></p>
    </div>
    <div class="float-left width20">
      <p>$<%=order.total_price%></p>
    </div>  
    <div class="float-left width10">
      <%= link_to "View", order_path(order.id), { role: "button" } %>
    </div>
  <% end %>
</div>
<div class="clear-both"></div>

app/views/orders/cart.html.erb
<% if @items.nil? || @items.empty? %>
  <p>No items in your cart</p>
<% else %>    
  <%= render "shared/items_summary" %>
  <p class="float-right margin-right9">
    SUBTOTAL:&nbsp; <b><%=@total%>$</b>
  </p>
  <div class="clear-both">  
    <button type="button" class="btn btn-default" id="empty-cart">EMPTY CART</button>
    <a href="/books/index_shop">
      <button type="button" class="btn btn-default margin-left5px">CONTINUE SHOPPING</button>
    </a>
    <div class="float-right  input-group">
      <input type="text" class="text-align-right width30 form-control" placeholder="Coupon code"/>
      <button type="button" class="btn btn-default border-top-left-radius0px border-bottom-left-radius0px">UPDATE</button>
      <a href="checkout">
        <button type="button" class="btn btn-default margin-left5px">CHECKOUT</button>    
      </a>
    </div>
  </div>
<% end %>    

app/views/orders/checkout.html.erb
<!-- multistep form -->
<form id="msform">
    <!-- progressbar -->
    <h3 class="margin-bottom5">CHECKOUT</h1>
    <ul id="progressbar">
        <li class="active">ADDRESS</li>
        <li>DELIVERY</li>
        <li>PAYMANT</li>
        <li>CONFIRM</li>
    </ul>
    <!-- fieldsets -->
    <fieldset>
        <h4 >ADDRESS</h4>
        <div class="width100 text-align-center display-inline-block">
            <div class="width33 text-align-center float-left">
                <h5>BILLING ADDRESS</h5>                        
                <div id="bil-addr" class="width95 align-center">
                    <input type="text" placeholder="First name" class="form-control remove-vertical-paddings" value= "<%= @first_name %>" id="firstname" >
                    <input type="text" placeholder="Last name" class="form-control remove-vertical-paddings" value= "<%= @last_name %>" id="lastname" >
                    <input type="text" placeholder="Street address" class="form-control remove-vertical-paddings" value= "<%= @street %>" id="bill-st-addr" >
                    <input type="text" placeholder="City" class="form-control remove-vertical-paddings" value= "<%= @city %>" id="bill-city-addr" >
                    <%= render partial: "shared/countries_dropdown", locals: { country: @country } %>
                    <input type="number" placeholder="Zip code" class="form-control remove-vertical-paddings" value= "<%= @zip %>" id="bill-zip" >
                    <input type="tel" placeholder="Phone number" class="form-control remove-vertical-paddings" value= "<%= @phone_number %>" id="bill-phone" >
                </div>
            </div>
            <div class="width33 text-align-center float-left">
                <div class="width95 align-center">                
                <h5>SHIPPING ADDRESS</h5>                        
                    <div class="height34px checkbox padding-top5px">
                        <label>
                            <input type="checkbox" id="use-billing-address" placeholder="First name" class="form-control" checked> Use billing address
                        </label>
                    </div>   
                    <div id="shipping-address" class="display-none">
                        <input type="text" placeholder="First name" class="form-control remove-vertical-paddings" id="ship-firstname">
                        <input type="text" placeholder="Last name" class="form-control remove-vertical-paddings" id="ship-lastname">
                        <input type="text" placeholder="Street address" class="form-control remove-vertical-paddings" id="ship-st-addr">
                        <input type="text" placeholder="City" class="form-control remove-vertical-paddings" id="ship-city-addr">
                        <%= render partial: "shared/countries_dropdown", locals: { country: nil } %>
                        <input type="number" placeholder="Zip code" class="form-control remove-vertical-paddings" id="ship-zip">
                    </div>
                </div>                        
            </div>
            <div class="width33 text-align-center float-left">
                <h5>ORDER SUMMARY</h5>                        
                <div class="width95 align-center">
                    <p>SUBTOTAL:&nbsp;<b><%=@total%>$</b></p>
                </div>                        
            </div>                    
        </div>
        <input id="to-delivery" type="button" name="next" class="clear-both next action-button" value="Next" >            
    </fieldset>
    <fieldset>        
        <h4>DELIVERY</h4>
        <div id="delivery-type" class="text-align-left width45 display-inline-block float-left">
            <label class="display-block">
                <input type="radio" name="delivery" value="5.00" checked >UPS Ground + $5.00
            </label>
            <label class="display-block">
                <input type="radio" name="delivery" value="10.00">UPS Two Days + $10.00
            </label>
            <label class="display-block">
                <input type="radio" name="delivery" value="15.00">UPS One Day + $15.00
            </label>
        </div>
        <div class="float-right text-align-right width45 display-inline-block">
            <h4 class="margin-top0px">ORDER SUMMARY</h4>
            <p>ITEM TOTAL:&nbsp;<b class="item-price">$<%=@total%></b></p>   
            <p>SHIPPING:&nbsp;<b class="ship-price">$5.00</b></p>                                     
            <p>ORDER TOTAL:&nbsp;<b class="total-price">$<%=@total+5%></b></p>   
        </div>            
        <div class="clear-both">        </div>
        <input id="back-to-address" type="button" name="previous" class="previous action-button" value="Previous" >
        <input type="button" name="next" class="next action-button" value="Next" >        
    </fieldset>
    <fieldset>
        <h4>PAYMANT</h4>
        <div id="paymant" class="text-align-left width55 display-inline-block float-left">
            <h4 class="margin-top0px">CREDIT CARD</h4>
            <input type="text" name="credit-card" placeholder="Card Number" class="width65 form-control remove-vertical-paddings">
            <p class="margin-bottom5px">Expiration date</p>
            <select id="card-exp-month" required class="form-control float-left width45">
                <option selected disabled>Month</option>
                <option value = "01">January</option>
                <option value = "02">February</option>
                <option value = "03">March</option>
                <option value = "04">April</option>
                <option value = "05">May</option>
                <option value = "06">June</option>
                <option value = "07">July</option>
                <option value = "08">August</option>
                <option value = "09">September</option>
                <option value = "10">October</option>
                <option value = "11">November</option>
                <option value = "12">December</option> 
            </select>
            <select id="card-exp-year" required class="form-control margin-left15px float-left width30">
                <option selected disabled>Year</option> 
                <% for i in Date.today.year..(Date.today.year+15) %>
                    <option value = "<%=i%>"><%=i%></option> 
                <% end %>
            </select>             
            <div class="clear-both"></div>
            <div class="margin-top20px">
                <input type="text" name="CVC" placeholder="Card Code" autocomplete="off" class="width45 form-control float-left remove-vertical-paddings">
                <a class="margin-top7px float-left margin-left5px" id="whats-it" title="The Card Verification Code, or CVC*, is an extra code printed on your debit or credit card. With most cards (Visa, MasterCard, bank cards, etc.) it is the final three digits of the number printed on the signature strip on the reverse of your card."> What's it? </a>
            </div>
        </div>
        <div class="float-right text-align-right width45 display-inline-block">
            <h4 class="margin-top0px">ORDER SUMMARY</h4>
            <p>ITEM TOTAL:&nbsp;<b class="item-price">$<%=@total%></b></p>   
            <p>SHIPPING:&nbsp;<b class="ship-price">$5.00</b></p>                                     
            <p>ORDER TOTAL:&nbsp;<b class="total-price">$<%=@total+5%></b></p>   
        </div>            
        <div class="clear-both">        </div>
        <input type="button" name="previous" class="previous action-button" value="Previous" />
        <input type="button" name="next" id="to-confirm" class="next action-button" value="Next" />
    </fieldset>
    <fieldset>
        <h4>CONFIRM</h4>
        <div class="display-inline-block width100 text-align-left">
            <div class="float-left width24" id="shipping-address-confirm">
                <h5><b>Shipping Address</b></h5>
                <p class="name"></p>
                <p class="street"></p>
                <p class="city"></p>
                <p class="country"></p>
            </div>
            <div class="float-left width24 margin-left1" id="billing-address-confirm">
                <h5><b>Billing Address</b></h5>
                <p class="name"></p>
                <p class="street"></p>
                <p class="city"></p>
                <p class="country"></p>
                <p class="phone"></p>                
            </div>
            <div class="float-left width20 margin-left1">
                <h5><b>Shipments</b></h5>
                <p id="ship-type-conf"> </p>
            </div>
            <div class="float-left width29 margin-left1">
                <h5><b>Payment Information</b></h5>
                <p id="card-num-conf"></p>
                <p id="card-exp-conf"></p>
            </div>            
        </div>
        <hr>
        <div class="margin-top30px text-align-left">
            <%= render "shared/items_summary" %>
        </div>
        <div class="float-right">
            <p>SUBTOTAL:&nbsp;<b class="item-price">$<%=@total%></b></p>
            <p>SHIPPING:&nbsp;<b class="ship-price">$5.00</b></p>
        </div>
        <hr class="clear-both">
        <p class="float-right">ORDER TOTAL:&nbsp;<b id="price" class="total-price">$<%=@total+5%></b></p>           
        <div class="clear-both"></div>
        <input type="button" name="previous" class="previous action-button" value="Previous" />
        <input type="button" name="submit-order" class="submit action-button" value="Confirm" />
    </fieldset>
</form>

<!-- jQuery easing plugin -->
<script src="http://thecodeplayer.com/uploads/js/jquery.easing.min.js" type="text/javascript"></script>

app/views/orders/index.html.erb
<h3>Orders</h4>
<% if (cookies[:ordered_items].nil? || cookies[:ordered_items].empty?) && @has_no_orders %>
  <h3>You have no orders yet</h3>
<% end %>
<% if (!cookies[:ordered_items].nil? && !cookies[:ordered_items].empty?) %>
  <h4 class="margin-bottom0px">IN PROGRESS</h4>
  <hr class="margin-top0px">
  <%= render partial: "shared/items_summary" %>
  <p class="float-right margin-right9 margin-bottom5">SUBTOTAL:&nbsp;<b><%=@total%>$</b></p>
<% end %>
<% unless @orders_in_progress.empty? %>
  <h4 class="margin-bottom0px clear-both">WAITING FOR PROCESSING</h4>
  <hr class="margin-top0px">
  <%= render partial: "orders_status", locals: { orders: @orders_in_progress } %>
<% end %>
<% unless @orders_in_delivery.empty? %>
  <h4 class="margin-bottom0px clear-both">IN DELIVERY</h4>
  <hr class="margin-top0px">
  <%= render partial: "orders_status", locals: { orders: @orders_in_delivery } %>
<% end %>
<% unless @orders_delivered.empty? %>
  <h4 class="margin-bottom0px clear-both">DELIVERED</h4>
  <hr class="margin-top0px">
  <%= render partial: "orders_status", locals: { orders: @orders_delivered } %>
<% end %>

app/views/orders/show.html.erb
<%= link_to "<< Back to orders", orders_path %>
<h3>Order <%=@order.number%> <small><%=@order.state%></small></h3>
<%= render partial: 'shared/items_summary' %>
<p class="float-right">SUBTOTAL:&nbsp;<b>$<%=@order.total_price - @shipping_price%></b></p>
<p class="float-right clear-both">SHIPPING:&nbsp;<b>$<%=@shipping_price%></b></p>
<hr class="clear-both">
<p class="float-right">ORDER TOTAL:&nbsp;<b>$<%=@order.total_price%></b></p>