config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_omniauth_user_session
  end  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'  

  root to: "books#index"

  resources :users do
    post 'change_billing_address', :to => 'users#change_billing_address', :as => :change_billing_address, on: :collection    
    post 'change_shipping_address', :to => 'users#change_shipping_address', :as => :change_shipping_address, on: :collection 
    post 'change_email', :to => 'users#change_email', :as => :change_email, on: :collection 
    post 'change_password', :to => 'users#change_password', :as => :change_password, on: :collection    
  end
  resources :books do
    get 'index_shop', on: :collection
  end

  resources :orders do
    get 'cart', on: :collection
    get 'checkout', on: :collection
  end
  
  post "ratings" => 'ratings#create', as: :create_rating

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  belongs_to :category
  has_many :ratings
  has_attached_file :cover, styles: { medium: "220x220#" }, :default_url => "default.png"

  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
  validates :author_id, presence: true
  validates :title, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :in_stock, presence: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.limit(20).order('updated_at DESC').includes(:author)
    if params[:no_layout] == 'true'
      render 'index', layout: false
    end
  end

  def show
    @book = Book.includes(:ratings).order('ratings.updated_at DESC').find(params[:id])
    @add_review = true
    @book.ratings.each do |rating|
      if current_user && rating.user_id == current_user.id
        @add_review = false
      end
    end
  end

  def index_shop
    active_page = 1
    unless (params[:active_page].nil? || params[active_page] == '')
      active_page = params[:active_page].to_i 
    end
    if !params[:category].nil? && params[:category] != ''
      @books = Book.joins(:category).where(categories: { title: params[:category] })
                   .limit(9).offset( (active_page-1)*9 ).order('price ASC')
      pages_number = Book.joins(:category)
      .where(categories: { title: params[:category] }).count(:all)
      category = params[:category]
    else
      @books = Book.limit(9).offset( (active_page-1)*9 ).order('price ASC')
      pages_number = Book.count(:all)      
    end
    pages_number = (pages_number / 9.0).ceil
    if params[:no_layout] == 'true'
      render 'index_shop', layout: false,
        locals: { active_page: active_page, pages_number: pages_number, category: category }
    else
      render 'index_shop',
        locals: { active_page: active_page, pages_number: pages_number, category: category }
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<div class="carousel slide width75 align-center" id="main">
  <!-- Wrapper for slides -->
  <% active = true %>
  <div class="carousel-inner">
    <% @books.each do |book| %>
      <% if active %>
        <div class="item active"> 
      <% else %>
        <div class="item">
      <% end %>
        <div class="width75 align-center">
          <div class="display-block">
            <h3 class="display-inline"><%= book.title %></h3>
            <div class="display-inline-block min-width50px min-height1px"> </div>
            <p class="display-inline">by <%= book.author.firstname %> <%= book.author.lastname %></p>
          </div>
          <div class="display-block min-height10px"></div>
            <div class="display-block">
              <a href=<%= "/books/#{book.id}" %>>
                <%= image_tag book.cover, { class: "display-inline", size: '160' } %>
              </a>
              <div class="min-width10px min-height1px display-inline-block"></div>
              <div class="display-inline position-absolute margin-right130px">
                <p class="break-word"><%= book.description %></p>
              </div>
            </div>
        </div>
      </div>
      <% active = false %>
    <% end %>
  </div>
 
  <!-- Controls -->
  <a class="left carousel-control" id="main-corusel-prev" role="button">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" id="main-corusel-next" role="button">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

app/views/books/index_shop.html.erb
<div id="main" class="width90 align-center"> 
  <div class="float-left width80">
    <% if category.nil? %>    
      <h3>Shop</h3>
    <% else %>
      <ul class="list-inline padding-bottom0px margin-bottom0px max-height20px">
        <li class="remove-sides-paddings"><a href="/books" class="internal-ref main-home-link">HOME</a></li>
        <li class="remove-sides-paddings"><p class="vertical-align-middle font-size20px">&raquo;&raquo;</p></li>
        <li class="remove-sides-paddings"><a href="/books/index_shop" class="internal-ref main-shop-link">SHOP</a></li>        
      </ul>
      <h3 class='margin-top0px'>Categories - <%=category%></h3>
    <% end %>
    <div class="row">
      <% @books.each_with_index do | book, index | %>
        <div class="width33 display-inline-block">
          <%= image_tag book.cover, { class: "display-block align-center", size: '160' } %>
          <%= link_to book.title, book_path(book), { class: "text-align-center display-block" } %>
          <p class="text-align-center"> $<%= book.price %> </p>
        </div>
        <% if (index + 1) % 3 == 0 %>
          <div class="clearfix visible-md-block"></div>
        <% end %>          
      <% end %>
    </div>
    <% if pages_number > 1 %>
      <div class="text-center">
        <ul class="pagination">
          <% if active_page != 1 %>
            <li class="pagination-item" id=<%="#{active_page-1}"%>><span>&laquo;</span></li>        
          <% else %>
            <li class="disabled"><span>&laquo;</span></li>
          <% end %>
          <% for i in 1..pages_number %>
            <% if (i == active_page) %>
              <li class="active pagination-item" id=<%= "#{i}" %> ><span><%= i %> <span class="sr-only">(current)</span></span></li>
            <% else %>
              <li class="pagination-item" id=<%= "#{i}" %>><span><%= i %></span></li>
            <% end %>
          <% end %>
          <% if active_page != pages_number %>
            <li class="pagination-item" id=<%="#{active_page+1}"%>><span>&raquo;</span></li>        
          <% else %>
            <li class="disabled"><span>&raquo;</span></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
  <div class="display-inline float-right width20">
    <h3 class="visibility-hidden">w</h3>
    <ul class="list-unstyled float-right" id="categories">
      <li><p class="font-size14px">SHOP BY CATEGORIES</p></li>
      <li><a href="/books/index_shop?category=Mobile+development" class="internal-ref" id="mobile-dev">Mobile development</a></li>
      <li><a href="/books/index_shop?category=Photography" class="internal-ref" id="photography">Photography</a></li>
      <li><a href="/books/index_shop?category=Web+design" class="internal-ref" id="web-design">Web design</a></li>
      <li><a href="/books/index_shop?category=Web+development" class="internal-ref" id="web-dev">Web development</a></li>    
    </ul>
  </div>
</div>

app/views/books/show.html.erb
<div class="main width65 align-center">
  <h3><%= @book.title %></h3>
  <%= image_tag @book.cover, { class: "display-inline", size: '220' } %>
  <div class="form-inline position-absolute margin-left30px display-inline-block width36">
    <div class="form-group">
      <label class="sr-only" for="price">Price</label>
      <span class="label label-default form-control font-size21px" id="price">
        <%= "$"+@book.price.to_s %>
      </span>    
    </div>
    <div class="form-group">
      <div class="input-group  margin-left55">
        <input id="book-qty" type="text" class="text-align-right width60px form-control spinedit" value='1'/>
        <span class="input-group-btn">
          <button class=" btn btn-default" id="add-to-cart" type="submit">ADD TO CART</button>
        </span>
      </div>
    </div>
    <div class="margin-top20px padding-all10px display-inline-block">
      <p class="break-word font-size16px"><%= @book.description %></p>
    </div> 
  </div>          
  <div class="margin-top30px margin-bottom15px">
    <h5 class="display-inline font-size16px"><strong>Reviews</strong></h5>
    <% if user_signed_in? %>
      <% if @add_review %>
        <%= link_to 'Add review', '#', { class: "margin-left30px dislpay-inline", id: "add-review"} %>
      <% end %>
    <% else %>
      <%= link_to 'Sign in to add review', '/users/sign_in', { class: "margin-left30px dislpay-inline"} %>    
    <% end %>    
  </div>
  <form class="form-horizontal display-none width65 align-center" id="review-form" role="form">
    <% for i in 1..5 %>
      <input name="star" id="star" type="radio" class="star review-rating" value=<%="#{i}"%> />
    <% end %>                    
    <div class="form-group">
      <label class="sr-only" for="short-feedback">Short Feedback</label>
      <input type="text" class="form-control width65" id="short-feedback" placeholder="Short feedback"/>
    </div>
      <textarea class="width90 form-control margin-bottom5px" id="comment" rows="3" placeholder="Review"></textarea>
    <button type="button" id="send-review" class="width10 btn btn-default margin-bottom10px">Send</button>
  </form>
  <% @book.ratings.each do |rating| %>
    <% user = User.where(id: rating.user_id).first %>
    <div class="row margin-left0px vertical-align-text-bottom">   
      <% for i in 1..5 %>
        <% if i==rating.mark %>
          <input name=<%="star#{rating.id}"%> type="radio" class="star" checked="checked" disabled="disabled"/>
        <% else %>
          <input name=<%="star#{rating.id}"%> type="radio" class="star"  disabled="disabled"/>
        <% end %>
      <% end %>
      <div class="col-xs-9">
        <p class="display-inline-block"><strong><%= rating.title %></strong></p>
        <p class="display-inline-block margin-left30px"><small>by <%= link_to user.firstname+' '+user.lastname, user_path(user.id) %></small></p>
      </div>
      <p class="display-inline-block text-align-right"><small><%= rating.updated_at.to_date.to_formatted_s(:long) %></small></p>        
    </div>
    <% if rating.comment != '' %>
      <div class="well well-lg">
        <p class="break-word margin-bottom0px"><%= rating.comment %></p>
      </div>    
    <% end %>
  <% end %>
</div>